# yamllint disable rule:line-length

inputs:
  lintball-version:
    description: "lintball version"
    required: false
    default: "v0.3.0"

  install-dependencies:
    description: "Install all dependencies"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Install lintball
      shell: bash
      run: |
        set -uexo pipefail

        curl -o- https://raw.githubusercontent.com/elijahr/lintball/${{ inputs.lintball-version }}/install.sh | bash

        find "${HOME}/.lintball"

        if [ "${{ inputs.install-dependencies }}" = "true" ]; then
          bash "${HOME}/.lintball/extras/install-deps.sh"
        fi
