# yamllint disable rule:line-length

name: Test
on:
  pull_request:
    brances: ["*"]
  push:
    brances: ["*"]

env:
  NODEJS_CHECK_SIGNATURES: no

jobs:
  test:
    name: bats tests

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.x"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/setup-node@v2
        with:
          python-version: "15.x"

      # Install nim
      - uses: asdf-vm/actions/install@v1

      - uses: ktmud/cached-dependencies@v1
        with:
          run: |
            cache-restore npm
            npm install --include=dev
            cache-save npm

            cache-restore pip
            pip install -r requirements.txt
            cache-save pip

            # cache-restore bundle
            gem install bundler
            bundle install --deployment
            # cache-save bundle

      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.NGROK_AUTH_TOKEN }}
