# yamllint disable rule:line-length

name: Test
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

jobs:
  tests:
    name: bats unit tests

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.x"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      # Install nim, via asdf - configured via .tool-versions
      - uses: asdf-vm/actions/install@v1

      # Install packages in a cache-friendly way, uses config from cache.js
      - uses: ktmud/cached-dependencies@v1
        with:
          run: |
            set -euxo pipefail

            cache-restore npmDev
            npm install --include=dev
            # seems to be necessary for node >= 15
            [ -n "$(which bats)" ] || npm link bats
            cache-save npmDev

            cache-restore pip
            python3 -m venv "${PWD}/python-env"
            python-env/bin/pip install -r requirements-pip.txt
            cache-save pip

            cache-restore gem
            gem install bundler
            cache-save gem

            bundle config set --local deployment 'true'
            cache-restore bundler
            bundle install
            cache-save bundler

            cache-restore brew
            brew install $(cat requirements-brew.txt)
            cache-save brew

            cache-restore apt
            sudo apt-get update
            sudo apt-get install -y $(cat requirements-apt.txt)
            cache-save apt

      - name: Run tests
        run: npm run test

  lint:
    name: lint

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      # Install packages in a cache-friendly way, uses config from cache.js
      - uses: ktmud/cached-dependencies@v1
        with:
          run: |
            set -euxo pipefail

            cache-restore npm
            npm install
            cache-save npm

            cache-restore brew
            brew install $(cat requirements-brew.txt)
            cache-save brew

      - name: Check for linter issues
        run: ./bin/lintball check
