# yamllint disable rule:line-length

name: Test
on:
  pull_request:
    brances: ["*"]
  push:
    brances: ["*"]

env:
  NODEJS_CHECK_SIGNATURES: no

jobs:
  test:
    name: bats tests

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.x"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/setup-node@v2
        with:
          python-version: "15.x"

      # Install nim
      - uses: asdf-vm/actions/install@v1

      - run: |
          set -euxo pipefail
          npm install --include=dev #&

          pip install -r requirements.txt #&

          gem install bundler
          bundle config set --local deployment 'true'
          bundle install #&
          # wait
          which bats || npm link bats

      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.NGROK_AUTH_TOKEN }}
