name: test

on: push

jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        include:
          - arch: armv7
            distro: buster
    steps:
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build on ${{ matrix.arch }}
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          run: |
            env
