# yamllint disable rule:line-length

name: Test
on:
  pull_request:
    brances: ["*"]
  push:
    brances: ["*"]

env:
  NODEJS_CHECK_SIGNATURES: no

jobs:
  test:
    name: bats tests

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.0.0"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/setup-node@v2
        with:
          python-version: "15.x"

      # Install nim
      - uses: asdf-vm/actions/install@v1

      # Install packages in a cache-friendly way, uses config from cache.js
      - uses: ktmud/cached-dependencies@master
        with:
          run: |
            set -euxo pipefail

            cache-restore npm
            npm install --include=dev
            cache-save npm

            cache-restore pip
            pip install -r requirements.txt
            cache-save pip

            cache-restore gem
            gem install bundler
            cache-save gem

            bundle config set --local deployment 'true'
            cache-restore bundler
            bundle install
            cache-save bundler

      - name: Install ShellCheck & shfmt
        run: brew install shellcheck shfmt

      - name: Run tests
        run: npm run test
