# yamllint disable rule:line-length

name: Test
on:
  pull_request:
    brances: ["*"]
  push:
    brances: ["*"]

env:
  NODEJS_CHECK_SIGNATURES: no

jobs:
  test:
    name: bats tests

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: asdf-vm/actions/setup@v1

      - name: Restore cached installs
        id: asdf-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.asdf/installs
            ~/.asdf/plugins
          key: asdf-${{ runner.os }}-${{ hashFiles('.tool-versions') }}

      - name: Install Python, Ruby, Nim, and NodeJS
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v1

      - name: Restore cached node modules
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: asdf-${{ runner.os }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('package-lock.json') }}

      - name: Install bats
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: |
          npm install --include=dev --verbose
          which bats || npm link bats

      - name: Test
        run: npm run test
