name: Test
on:
  pull_request:
    brances: ["*"]
  push:
    brances: ["*"]

jobs:
  test:
    name: bats tests

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: elijahr/lintball/setup@${{ github.sha }}
        with:
          lintball-version: ${{ github.sha }}

      - name: Test
        run: npm run test

  install:
    name: test installation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check bash
        shell: bash
        run: |
          set -uexo pipefail
          export LINTBALL_VERSION="$GITHUB_REF"
          ./install.sh
          test -n "'$(grep LINTBALL_DIR "${HOME}/.bashrc")'"
          test -n "'$(grep LINTBALL_DIR "${HOME}/.bash_profile")'"
          . "${HOME}/.lintball/lintball.sh"
          test -n "${LINTBALL_DIR:-}"
          test -n "$(which lintball)"
          test -n "$(which lintball --write)"
          test -n "$(which install-lintball-githooks)"

      - name: Install fish
        run: sudo apt-get install fish

      - name: Check fish
        shell: fish {0}
        run: |
          set fish_trace 1 2
          set -gx LINTBALL_VERSION "$GITHUB_REF"
          bash ./install.sh; or exit 1
          test -n "'(grep LINTBALL_DIR "$HOME/.config/fish/config.fish")'"; \
            or exit 1
          ls -al "$HOME/.lintball/lintball.fish"
          source "$HOME/.lintball/lintball.fish"; or exit 1
          test -n "$LINTBALL_DIR"; or exit
          test -n "(which lintball)"; or exit 1
          test -n "(which lintball --write)"; or exit 1
          test -n "(which install-lintball-githooks)"; or exit 1

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: elijahr/lintball/setup@${{ github.sha }}
        with:
          lintball-version: ${{ github.sha }}

      - name: check
        run: lintball
